[general]
import = ["./themes/catppuccin-dark.toml"]

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
size = 15

[window]
opacity = 1
dynamic_title = true

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
