[general]
import = ["./themes/catppuccin-dark.toml"]

[font]
normal = { family = "Terminess Nerd Font Mono", style = "Normal" }
size = 18

[window]
opacity = 1
dynamic_title = true

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
