[general]
import = ["./themes/rose-pine.toml"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16

[window]
opacity = 0.85
dynamic_title = true

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
