# Better prefix
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Easy config refresh
unbind r
bind r source-file ~/.tmux.conf

# Kill pane and session
bind x kill-pane
bind X kill-session

# Support for true-color
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Tc'

# 1-index windows and panes
set -g base-index 1
set -g pane-base-index 1

# Better window splitting
unbind %
bind | split-window -h # vertical
unbind '"'
bind - split-window -v # horizontal (yeah, it's the other way around lmfao)

### VIM MOTIONS AND NEOVIM INTEGRATION ###

# Requirements for using with Neovim
set -sg escape-time 0
set -g focus-events on

# Resize panes
bind -r C-h resize-pane -L 10
bind -r C-j resize-pane -D 10
bind -r C-k resize-pane -U 10
bind -r C-l resize-pane -R 10

# Switch panes
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Act like vim
set-window-option -g mode-keys vi
bind [ copy-mode
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

######

# Mouse support (for when I'm lazy)
set -g mouse on

# Status line colors
set -g status-style bg='#19615B',fg='#eee8d5'
