#!/usr/bin/env bash
CONFIG_FILE_NAME="tmux-sessionizer.conf"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-sessionizer"
CONFIG_FILE="$CONFIG_DIR/$CONFIG_FILE_NAME"

[[ -f $CONFIG_FILE ]] && source "$CONFIG_FILE"
[[ -f $CONFIG_FILE_NAME ]] && source "$CONFIG_FILE_NAME"

log() {
  [[ $TS_LOG == "echo" ]] && echo "$*"
  [[ $TS_LOG == "file" ]] && echo "$*" >>"$TS_LOG_FILE"
}

sanity_check() {
  for cmd in tmux fzf fd; do
    if ! command -v $cmd &>/dev/null; then
      echo "Error: $cmd is not installed."
      exit 1
    fi
  done
}

switch_to() {
  if [[ -z $TMUX ]]; then
    tmux attach-session -t "$1"
  else
    tmux switch-client -t "$1"
  fi
}

has_session() {
  tmux list-sessions | grep -q "^$1:"
}

is_tmux_running() {
  pgrep tmux >/dev/null
}

find_dirs() {
  tmux list-sessions -F "[TMUX] #{session_name}" 2>/dev/null | grep -vFx "[TMUX] $(tmux display-message -p '#S' 2>/dev/null)"
  fd --type d --hidden --exclude .git --exclude .cache --max-depth 4 . "$HOME"
}

create_custom_session() {
  local s_name="$1"
  local s_dir="$2"

  # Panel 1: Yazi
  tmux new-session -ds "$s_name" -c "#s_dir" -n files "yazi"
  # Panel 2: Docker
  tmux new-window -t "$s_name:2" -n docker -c "$s_dir" "lazydocker"
  # Panel 3: Kubernetes
  tmux new-window -t "$s_name:3" -n kubernetes -c "$s_dir" "k9s"
  # Panel 4: Btop
  tmux new-window -t "$s_name:4" -n system -c "$s_dir" "btop"
  # Panel 5: Shell
  tmux new-window -t "$s_name" -c "$s_dir" -n bash
  # Focus on the first panel on session start
  tmux select-window -t "$s_name:1"
}

sanity_check

if [[ -n $user_selected ]]; then
  selected="$user_selected"
elif [[ $# -eq 1 ]]; then
  selected="$1"
else
  selected=$(find_dirs | fzf --prompt="📂 Project: " --preview "ls -F {}")
fi

[[ -z $selected ]] && exit 0

[[ $selected =~ ^\[TMUX\]\ (.+)$ ]] && selected="${BASH_REMATCH[1]}"
[[ $selected == "." ]] && selected="$PWD"

selected=$(realpath "$selected")
selected_name=$(basename "$selected" | tr . _)

if ! is_tmux_running || ! has_session "$selected_name"; then
  create_custom_session "$selected_name" "$selected"
fi

switch_to "$selected_name"
