# Palette: kdheepak/monochrome.nvim (dark)

[colors.primary]
foreground = "#c0c0c0"
background = "#000000"
dim_foreground = "#707070"
bright_foreground = "#e0e0e0"

[colors.cursor]
text = "#1c1c1c"
cursor = "#c0c0c0"

[colors.vi_mode_cursor]
text = "#1c1c1c"
cursor = "#c0c0c0"

[colors.search.matches]
foreground = "#707070"
background = "#2e2e2e"

[colors.search.focused_match]
foreground = "#1c1c1c"
background = "#e0e0e0"

[colors.hints.start]
foreground = "#707070"
background = "#242424"

[colors.hints.end]
foreground = "#505050"
background = "#242424"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#c0c0c0"
background = "#242424"

[colors.selection]
text = "#1c1c1c"
background = "#909090"
